# .streamlit/secrets.toml

[snowflake]
account = "STMNGJB-JGB89962"
user = "ROYCHOI1012"
password = "Chldmsfuf1012!"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS"
schema = "GRANDATA"
